// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalCommitAPIClient is the client API for InternalCommitAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalCommitAPIClient interface {
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*Response, error)
	Precommit(ctx context.Context, in *PrecommitRequest, opts ...grpc.CallOption) (*Response, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Response, error)
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*Response, error)
	// Decision lets an in-doubt cohort ask the coordinator for the recorded
	// outcome of a given height (2PC termination protocol).
	Decision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
}

type internalCommitAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalCommitAPIClient(cc grpc.ClientConnInterface) InternalCommitAPIClient {
	return &internalCommitAPIClient{cc}
}

func (c *internalCommitAPIClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.InternalCommitAPI/Propose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalCommitAPIClient) Precommit(ctx context.Context, in *PrecommitRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.InternalCommitAPI/Precommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalCommitAPIClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.InternalCommitAPI/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalCommitAPIClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.InternalCommitAPI/Abort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalCommitAPIClient) Decision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, "/schema.InternalCommitAPI/Decision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalCommitAPIServer is the server API for InternalCommitAPI service.
// All implementations must embed UnimplementedInternalCommitAPIServer
// for forward compatibility
type InternalCommitAPIServer interface {
	Propose(context.Context, *ProposeRequest) (*Response, error)
	Precommit(context.Context, *PrecommitRequest) (*Response, error)
	Commit(context.Context, *CommitRequest) (*Response, error)
	Abort(context.Context, *AbortRequest) (*Response, error)
	// Decision lets an in-doubt cohort ask the coordinator for the recorded
	// outcome of a given height (2PC termination protocol).
	Decision(context.Context, *DecisionRequest) (*DecisionResponse, error)
	mustEmbedUnimplementedInternalCommitAPIServer()
}

// UnimplementedInternalCommitAPIServer must be embedded to have forward compatible implementations.
type UnimplementedInternalCommitAPIServer struct {
}

func (UnimplementedInternalCommitAPIServer) Propose(context.Context, *ProposeRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedInternalCommitAPIServer) Precommit(context.Context, *PrecommitRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Precommit not implemented")
}
func (UnimplementedInternalCommitAPIServer) Commit(context.Context, *CommitRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedInternalCommitAPIServer) Abort(context.Context, *AbortRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedInternalCommitAPIServer) Decision(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decision not implemented")
}
func (UnimplementedInternalCommitAPIServer) mustEmbedUnimplementedInternalCommitAPIServer() {}

// UnsafeInternalCommitAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalCommitAPIServer will
// result in compilation errors.
type UnsafeInternalCommitAPIServer interface {
	mustEmbedUnimplementedInternalCommitAPIServer()
}

func RegisterInternalCommitAPIServer(s grpc.ServiceRegistrar, srv InternalCommitAPIServer) {
	s.RegisterService(&InternalCommitAPI_ServiceDesc, srv)
}

func _InternalCommitAPI_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalCommitAPIServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.InternalCommitAPI/Propose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalCommitAPIServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalCommitAPI_Precommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrecommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalCommitAPIServer).Precommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.InternalCommitAPI/Precommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalCommitAPIServer).Precommit(ctx, req.(*PrecommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalCommitAPI_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalCommitAPIServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.InternalCommitAPI/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalCommitAPIServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalCommitAPI_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalCommitAPIServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.InternalCommitAPI/Abort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalCommitAPIServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalCommitAPI_Decision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalCommitAPIServer).Decision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.InternalCommitAPI/Decision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalCommitAPIServer).Decision(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalCommitAPI_ServiceDesc is the grpc.ServiceDesc for InternalCommitAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalCommitAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schema.InternalCommitAPI",
	HandlerType: (*InternalCommitAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _InternalCommitAPI_Propose_Handler,
		},
		{
			MethodName: "Precommit",
			Handler:    _InternalCommitAPI_Precommit_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _InternalCommitAPI_Commit_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _InternalCommitAPI_Abort_Handler,
		},
		{
			MethodName: "Decision",
			Handler:    _InternalCommitAPI_Decision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
