// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vadiminshakov/committer/core/coordinator (interfaces: wal)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_wal.go -package=mocks . wal
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockwal is a mock of wal interface.
type Mockwal struct {
	ctrl     *gomock.Controller
	recorder *MockwalMockRecorder
	isgomock struct{}
}

// MockwalMockRecorder is the mock recorder for Mockwal.
type MockwalMockRecorder struct {
	mock *Mockwal
}

// NewMockwal creates a new mock instance.
func NewMockwal(ctrl *gomock.Controller) *Mockwal {
	mock := &Mockwal{ctrl: ctrl}
	mock.recorder = &MockwalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwal) EXPECT() *MockwalMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Mockwal) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockwalMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockwal)(nil).Close))
}

// Write mocks base method.
func (m *Mockwal) Write(key string, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockwalMockRecorder) Write(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*Mockwal)(nil).Write), key, value)
}
