// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vadiminshakov/committer/core/cohort/commitalgo (interfaces: DecisionRequester)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_decision_requester.go -package=mocks -mock_names=DecisionRequester=MockDecisionRequester . DecisionRequester
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/vadiminshakov/committer/core/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockDecisionRequester is a mock of DecisionRequester interface.
type MockDecisionRequester struct {
	ctrl     *gomock.Controller
	recorder *MockDecisionRequesterMockRecorder
	isgomock struct{}
}

// MockDecisionRequesterMockRecorder is the mock recorder for MockDecisionRequester.
type MockDecisionRequesterMockRecorder struct {
	mock *MockDecisionRequester
}

// NewMockDecisionRequester creates a new mock instance.
func NewMockDecisionRequester(ctrl *gomock.Controller) *MockDecisionRequester {
	mock := &MockDecisionRequester{ctrl: ctrl}
	mock.recorder = &MockDecisionRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecisionRequester) EXPECT() *MockDecisionRequesterMockRecorder {
	return m.recorder
}

// Decision mocks base method.
func (m *MockDecisionRequester) Decision(ctx context.Context, height uint64) (dto.Outcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decision", ctx, height)
	ret0, _ := ret[0].(dto.Outcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decision indicates an expected call of Decision.
func (mr *MockDecisionRequesterMockRecorder) Decision(ctx, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decision", reflect.TypeOf((*MockDecisionRequester)(nil).Decision), ctx, height)
}
