// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vadiminshakov/committer/v2/core/coordinator (interfaces: wal,Cohort)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_coordinator.go -package=mocks -mock_names=wal=MockCoordinatorWAL,Cohort=MockCoordinatorCohort . wal,Cohort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/vadiminshakov/committer/v2/core/dto"
	wal "github.com/vadiminshakov/committer/v2/io/wal"
	gomock "go.uber.org/mock/gomock"
)

// MockCoordinatorWAL is a mock of wal interface.
type MockCoordinatorWAL struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorWALMockRecorder
	isgomock struct{}
}

// MockCoordinatorWALMockRecorder is the mock recorder for MockCoordinatorWAL.
type MockCoordinatorWALMockRecorder struct {
	mock *MockCoordinatorWAL
}

// NewMockCoordinatorWAL creates a new mock instance.
func NewMockCoordinatorWAL(ctrl *gomock.Controller) *MockCoordinatorWAL {
	mock := &MockCoordinatorWAL{ctrl: ctrl}
	mock.recorder = &MockCoordinatorWALMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinatorWAL) EXPECT() *MockCoordinatorWALMockRecorder {
	return m.recorder
}

// Recover mocks base method.
func (m *MockCoordinatorWAL) Recover(applyFn func(string, []byte) error) (*wal.RecoveryState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", applyFn)
	ret0, _ := ret[0].(*wal.RecoveryState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recover indicates an expected call of Recover.
func (mr *MockCoordinatorWALMockRecorder) Recover(applyFn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockCoordinatorWAL)(nil).Recover), applyFn)
}

// Write mocks base method.
func (m *MockCoordinatorWAL) Write(key string, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockCoordinatorWALMockRecorder) Write(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockCoordinatorWAL)(nil).Write), key, value)
}

// MockCoordinatorCohort is a mock of Cohort interface.
type MockCoordinatorCohort struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorCohortMockRecorder
	isgomock struct{}
}

// MockCoordinatorCohortMockRecorder is the mock recorder for MockCoordinatorCohort.
type MockCoordinatorCohortMockRecorder struct {
	mock *MockCoordinatorCohort
}

// NewMockCoordinatorCohort creates a new mock instance.
func NewMockCoordinatorCohort(ctrl *gomock.Controller) *MockCoordinatorCohort {
	mock := &MockCoordinatorCohort{ctrl: ctrl}
	mock.recorder = &MockCoordinatorCohortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinatorCohort) EXPECT() *MockCoordinatorCohortMockRecorder {
	return m.recorder
}

// Addr mocks base method.
func (m *MockCoordinatorCohort) Addr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Addr")
	ret0, _ := ret[0].(string)
	return ret0
}

// Addr indicates an expected call of Addr.
func (mr *MockCoordinatorCohortMockRecorder) Addr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Addr", reflect.TypeOf((*MockCoordinatorCohort)(nil).Addr))
}

// ApplyFinalDecision mocks base method.
func (m *MockCoordinatorCohort) ApplyFinalDecision(arg0 context.Context, arg1 dto.FinalDecision) (dto.ParticipantReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyFinalDecision", arg0, arg1)
	ret0, _ := ret[0].(dto.ParticipantReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyFinalDecision indicates an expected call of ApplyFinalDecision.
func (mr *MockCoordinatorCohortMockRecorder) ApplyFinalDecision(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyFinalDecision", reflect.TypeOf((*MockCoordinatorCohort)(nil).ApplyFinalDecision), arg0, arg1)
}

// Close mocks base method.
func (m *MockCoordinatorCohort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCoordinatorCohortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCoordinatorCohort)(nil).Close))
}

// Precommit mocks base method.
func (m *MockCoordinatorCohort) Precommit(arg0 context.Context, arg1 uint64) (dto.ParticipantReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Precommit", arg0, arg1)
	ret0, _ := ret[0].(dto.ParticipantReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Precommit indicates an expected call of Precommit.
func (mr *MockCoordinatorCohortMockRecorder) Precommit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Precommit", reflect.TypeOf((*MockCoordinatorCohort)(nil).Precommit), arg0, arg1)
}

// Propose mocks base method.
func (m *MockCoordinatorCohort) Propose(arg0 context.Context, arg1 dto.Proposal) (dto.ParticipantReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Propose", arg0, arg1)
	ret0, _ := ret[0].(dto.ParticipantReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Propose indicates an expected call of Propose.
func (mr *MockCoordinatorCohortMockRecorder) Propose(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Propose", reflect.TypeOf((*MockCoordinatorCohort)(nil).Propose), arg0, arg1)
}
