// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vadiminshakov/committer/v2/core/cohort (interfaces: Resource)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_resource.go -package=mocks . Resource
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/vadiminshakov/committer/v2/core/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockResource is a mock of Resource interface.
type MockResource struct {
	ctrl     *gomock.Controller
	recorder *MockResourceMockRecorder
	isgomock struct{}
}

// MockResourceMockRecorder is the mock recorder for MockResource.
type MockResourceMockRecorder struct {
	mock *MockResource
}

// NewMockResource creates a new mock instance.
func NewMockResource(ctrl *gomock.Controller) *MockResource {
	mock := &MockResource{ctrl: ctrl}
	mock.recorder = &MockResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResource) EXPECT() *MockResourceMockRecorder {
	return m.recorder
}

// Abort mocks base method.
func (m *MockResource) Abort(ctx context.Context, height uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abort", ctx, height)
	ret0, _ := ret[0].(error)
	return ret0
}

// Abort indicates an expected call of Abort.
func (mr *MockResourceMockRecorder) Abort(ctx, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abort", reflect.TypeOf((*MockResource)(nil).Abort), ctx, height)
}

// Commit mocks base method.
func (m *MockResource) Commit(ctx context.Context, tx dto.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockResourceMockRecorder) Commit(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockResource)(nil).Commit), ctx, tx)
}

// Prepare mocks base method.
func (m *MockResource) Prepare(ctx context.Context, tx dto.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prepare indicates an expected call of Prepare.
func (mr *MockResourceMockRecorder) Prepare(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockResource)(nil).Prepare), ctx, tx)
}
