// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommitType int32

const (
	CommitType_TWO_PHASE_COMMIT   CommitType = 0
	CommitType_THREE_PHASE_COMMIT CommitType = 1
)

var CommitType_name = map[int32]string{
	0: "TWO_PHASE_COMMIT",
	1: "THREE_PHASE_COMMIT",
}

var CommitType_value = map[string]int32{
	"TWO_PHASE_COMMIT":   0,
	"THREE_PHASE_COMMIT": 1,
}

func (x CommitType) String() string {
	return proto.EnumName(CommitType_name, int32(x))
}

func (CommitType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

type Type int32

const (
	Type_ACK  Type = 0
	Type_NACK Type = 1
)

var Type_name = map[int32]string{
	0: "ACK",
	1: "NACK",
}

var Type_value = map[string]int32{
	"ACK":  0,
	"NACK": 1,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

type ProposeRequest struct {
	Key                  string     `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte     `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	CommitType           CommitType `protobuf:"varint,3,opt,name=CommitType,proto3,enum=schema.CommitType" json:"CommitType,omitempty"`
	Index                uint64     `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProposeRequest) Reset()         { *m = ProposeRequest{} }
func (m *ProposeRequest) String() string { return proto.CompactTextString(m) }
func (*ProposeRequest) ProtoMessage()    {}
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *ProposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeRequest.Unmarshal(m, b)
}
func (m *ProposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeRequest.Marshal(b, m, deterministic)
}
func (m *ProposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeRequest.Merge(m, src)
}
func (m *ProposeRequest) XXX_Size() int {
	return xxx_messageInfo_ProposeRequest.Size(m)
}
func (m *ProposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeRequest proto.InternalMessageInfo

func (m *ProposeRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ProposeRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProposeRequest) GetCommitType() CommitType {
	if m != nil {
		return m.CommitType
	}
	return CommitType_TWO_PHASE_COMMIT
}

func (m *ProposeRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Response struct {
	Type                 Type     `protobuf:"varint,1,opt,name=Type,proto3,enum=schema.Type" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_ACK
}

type PrecommitRequest struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrecommitRequest) Reset()         { *m = PrecommitRequest{} }
func (m *PrecommitRequest) String() string { return proto.CompactTextString(m) }
func (*PrecommitRequest) ProtoMessage()    {}
func (*PrecommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *PrecommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrecommitRequest.Unmarshal(m, b)
}
func (m *PrecommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrecommitRequest.Marshal(b, m, deterministic)
}
func (m *PrecommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrecommitRequest.Merge(m, src)
}
func (m *PrecommitRequest) XXX_Size() int {
	return xxx_messageInfo_PrecommitRequest.Size(m)
}
func (m *PrecommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrecommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrecommitRequest proto.InternalMessageInfo

func (m *PrecommitRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type CommitRequest struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Entry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("schema.CommitType", CommitType_name, CommitType_value)
	proto.RegisterEnum("schema.Type", Type_name, Type_value)
	proto.RegisterType((*ProposeRequest)(nil), "schema.ProposeRequest")
	proto.RegisterType((*Response)(nil), "schema.Response")
	proto.RegisterType((*PrecommitRequest)(nil), "schema.PrecommitRequest")
	proto.RegisterType((*CommitRequest)(nil), "schema.CommitRequest")
	proto.RegisterType((*Entry)(nil), "schema.Entry")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0xbb, 0xff, 0xa4, 0x6f, 0x43, 0x5b, 0x96, 0xe1, 0x6f, 0x89, 0x9e, 0x42, 0x41, 0x09,
	0x45, 0x2a, 0xb6, 0x07, 0xc1, 0x5b, 0x09, 0x81, 0x4a, 0xa9, 0x0d, 0x6b, 0xd0, 0x63, 0xa9, 0x75,
	0xc1, 0x52, 0xdb, 0x8d, 0x49, 0x2a, 0xe6, 0xea, 0x37, 0xf4, 0x1b, 0x49, 0x76, 0x9b, 0x37, 0x54,
	0xf0, 0xb6, 0xcf, 0xce, 0xcc, 0x6f, 0xf3, 0x3c, 0x13, 0x68, 0x85, 0xab, 0x67, 0xbe, 0x5d, 0x0e,
	0xfc, 0x40, 0x44, 0x02, 0x6b, 0x4a, 0xf5, 0x3e, 0x08, 0x74, 0xdc, 0x40, 0xf8, 0x22, 0xe4, 0x8c,
	0xbf, 0xee, 0x79, 0x18, 0x21, 0x05, 0x6d, 0xca, 0x63, 0x83, 0x98, 0xc4, 0x6a, 0xb2, 0xe4, 0x88,
	0xff, 0xa1, 0x7a, 0xbf, 0x7c, 0xd9, 0x73, 0xe3, 0x9f, 0x49, 0xac, 0x16, 0x53, 0x02, 0x87, 0x00,
	0xb6, 0xd8, 0x6e, 0xd7, 0x91, 0x17, 0xfb, 0xdc, 0xd0, 0x4c, 0x62, 0x75, 0x86, 0x38, 0x38, 0xbc,
	0x92, 0x57, 0x58, 0xa1, 0x2b, 0x21, 0xad, 0x77, 0x4f, 0xfc, 0xdd, 0xd0, 0x4d, 0x62, 0xe9, 0x4c,
	0x89, 0xde, 0x39, 0x34, 0x18, 0x0f, 0x7d, 0xb1, 0x0b, 0x39, 0x9a, 0xa0, 0x4b, 0x1e, 0x91, 0xbc,
	0x56, 0xca, 0x93, 0x24, 0x59, 0xe9, 0x59, 0x40, 0xdd, 0x80, 0xaf, 0x24, 0x34, 0xfd, 0xe6, 0x8c,
	0x4b, 0x8a, 0xdc, 0x53, 0x68, 0xdb, 0x7f, 0x68, 0xbb, 0x80, 0xaa, 0xb3, 0x8b, 0x82, 0x38, 0x71,
	0xbe, 0xc9, 0x9d, 0x6f, 0x94, 0xf3, 0xb7, 0xa2, 0x73, 0x29, 0xfa, 0xd7, 0x50, 0xf6, 0x44, 0xbd,
	0x87, 0xf9, 0xc2, 0x9d, 0x8c, 0xef, 0x9c, 0x85, 0x3d, 0x9f, 0xcd, 0x6e, 0x3c, 0x5a, 0xc1, 0x2e,
	0xa0, 0x37, 0x61, 0x8e, 0x53, 0xbe, 0x27, 0xfd, 0x63, 0xe5, 0x0f, 0xeb, 0xa0, 0x8d, 0xed, 0x29,
	0xad, 0x60, 0x03, 0xf4, 0xdb, 0xe4, 0x44, 0x86, 0x9f, 0x04, 0x6a, 0x8a, 0x8b, 0x23, 0xa8, 0x1f,
	0xb6, 0x82, 0xdd, 0x34, 0x82, 0xf2, 0x9a, 0x4e, 0x68, 0x7a, 0x9f, 0x45, 0x77, 0x05, 0xcd, 0x2c,
	0x18, 0x34, 0xf2, 0xb1, 0x72, 0x56, 0x3f, 0x0c, 0x5e, 0x66, 0xef, 0x1e, 0x95, 0xf7, 0xf7, 0xfb,
	0xc8, 0x19, 0x68, 0xee, 0x3e, 0xc2, 0x76, 0x5a, 0x90, 0x01, 0x7e, 0xef, 0x7b, 0xac, 0xc9, 0xdf,
	0x6d, 0xf4, 0x15, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x02, 0xd1, 0x1a, 0x7e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommitClient is the peer API for Commit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommitClient interface {
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*Response, error)
	Precommit(ctx context.Context, in *PrecommitRequest, opts ...grpc.CallOption) (*Response, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Response, error)
	Put(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Response, error)
}

type commitClient struct {
	cc *grpc.ClientConn
}

func NewCommitClient(cc *grpc.ClientConn) CommitClient {
	return &commitClient{cc}
}

func (c *commitClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.Commit/Propose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commitClient) Precommit(ctx context.Context, in *PrecommitRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.Commit/Precommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commitClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.Commit/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commitClient) Put(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/schema.Commit/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommitServer is the server API for Commit service.
type CommitServer interface {
	Propose(context.Context, *ProposeRequest) (*Response, error)
	Precommit(context.Context, *PrecommitRequest) (*Response, error)
	Commit(context.Context, *CommitRequest) (*Response, error)
	Put(context.Context, *Entry) (*Response, error)
}

// UnimplementedCommitServer can be embedded to have forward compatible implementations.
type UnimplementedCommitServer struct {
}

func (*UnimplementedCommitServer) Propose(ctx context.Context, req *ProposeRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (*UnimplementedCommitServer) Precommit(ctx context.Context, req *PrecommitRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Precommit not implemented")
}
func (*UnimplementedCommitServer) Commit(ctx context.Context, req *CommitRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (*UnimplementedCommitServer) Put(ctx context.Context, req *Entry) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}

func RegisterCommitServer(s *grpc.Server, srv CommitServer) {
	s.RegisterService(&_Commit_serviceDesc, srv)
}

func _Commit_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.Commit/Propose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commit_Precommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrecommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).Precommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.Commit/Precommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).Precommit(ctx, req.(*PrecommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commit_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.Commit/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commit_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.Commit/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).Put(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.Commit",
	HandlerType: (*CommitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _Commit_Propose_Handler,
		},
		{
			MethodName: "Precommit",
			Handler:    _Commit_Precommit_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Commit_Commit_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Commit_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
